services:
  flyway:
    image: outbox-migrations:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://outbox-pattern-outbox-db-1/${DB_NAME}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    networks:
      - outbox-network
    depends_on: [outbox-db]
  outbox-db:
    image: postgres:12.2-alpine
    ports:
      - 57882:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - outbox-network
volumes:
  db-volume:

networks:
  outbox-network:
    driver: bridge