services:
#  load-balancer:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    networks:
#      - lp-networks
#    depends_on:
#      - long-polling-service1
  lp-service:
    image: lp-service:v1
    ports:
      - "8188:8080"
    networks:
      - lp-networks
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lp-service-lp-db-1:57892/lp-service
  lp-db:
    image: postgres:12.2-alpine
    ports:
      - 57892:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - lp-networks
volumes:
  db-volume:

networks:
  lp-networks:
    driver: bridge
